### ISSUE TITLE
In HTML Markup the cared doesn't move over tags with a '-' in them when using crtl+left/right

### ISSUE THREAD

**Issue by adickenscheidt** [maptz/Maptz.VSCode.Extensions.CamelCaseNavigation#11]
When placing the cared right of a tag (e.g. <text-box>) and pressing ctrl+left, the cared stops in front of the dash and doesn't move over it unless you use only the left key, which is problematic because I generally use ctrl+left/right to navigate through markup more quickly.

**Comment by maptz** [comment]
I'll look into this today.

**Comment by maptz** [comment]
Hi,

I'm unable to reproduce this. Can you give me an example?
