### ISSUE TITLE
Default Shortcuts

### ISSUE THREAD

**Issue by valerius257** [maptz/Maptz.VSCode.Extensions.CamelCaseNavigation#12]
It's a bad practice to override default shortcuts.

**Comment by Noitidart** [comment]
It only overwrites on Windows. On mac it is not an overwrite. It is easy to change it though. I actually like the override, but if you want to change to use Alt for example simply do this:

![](http://i.imgur.com/rlKCba3.png)

**Comment by maptz** [comment]
Hey @valerius257 , I agree that it's bad form. What are your suggestion? To change the default key-mapping?

**Comment by Noitidart** [comment]
@maptz can we have default key mapping of "Ctrl" on mac? And "Alt" on Windows? I thought extensions only allowed default key mapping for all platforms.

**Comment by valerius257** [comment]
The issue with solution proposed by @Noitidart is that it does not restore default behavior, it just adds additional shortcuts for CamelCase navigation.
To restore default behavior it's also necessary to add default shortcuts for word navigation to your vscode keybindings config.

**Comment by valerius257** [comment]
The problem is that most of the convenient keybindings are already used by vscode (including alt+left and alt+right).
My proposal is to not to include default shortcuts but to add instruction how to add them, so user can decide which shortcuts to use.

Personally I use the following configuration (on Windows):

```json
{ "key": "alt+left",              "command": "extension.moveCamelLeftCommand",
                                     "when": "editorTextFocus" },
{ "key": "alt+right",             "command": "extension.moveCamelRightCommand",
                                     "when": "editorTextFocus" },
{ "key": "shift+alt+right",       "command": "extension.extendCamelRightCommand",
                                     "when": "editorTextFocus" },
{ "key": "shift+alt+left",        "command": "extension.extendCamelLeftCommand",
                                     "when": "editorTextFocus" },
// Restore Default Keybindings
{ "key": "ctrl+left",             "command": "cursorWordStartLeft",
                                     "when": "editorTextFocus" },
{ "key": "ctrl+right",            "command": "cursorWordEndRight",
                                     "when": "editorTextFocus" },
{ "key": "ctrl+shift+left",       "command": "cursorWordStartLeftSelect",
                                     "when": "editorTextFocus" },
{ "key": "ctrl+shift+right",      "command": "cursorWordEndRightSelect",
                                     "when": "editorTextFocus" }
```

**Comment by Noitidart** [comment]
@valerius257 If you use the key binding helper, "clicking the pencil" it will add a 

```
{ "key": "ctrl+left",              "command": "-extension.moveCamelLeftCommand",
                                     "when": "editorTextFocus" },
{ "key": "alt+left",              "command": "extension.moveCamelLeftCommand",
                                     "when": "editorTextFocus" },
```

See above the first one has a `-` prefix, that removes that. So it restores he default keybindings.

When I install extensions, I usually don't understand what it does until I actually use it. Having to set up the key bindings on install will be deterrent to users. Well this is just my personal experience.

**Comment by maptz** [comment]
Yes. I'm not really sure what the  right solution is here. I fear that removing the default keybinding will make the functionality less discoverable. 

@Noitidart , I've tried adding a - before the commandname, and it shows an error. Is this a built-in feature? Which version was it introduced?

Does anyone know how to show an info page when installing the extension?

**Comment by Noitidart** [comment]
@maptz I'm not sure which version introduced this. But I use the auto record feature to record hotkeys, and it auto does that `-` thing for me. It results in no conflicts so it works :)
