### ISSUE TITLE
MoveCamelRightCommand doesn't scroll screen right

### ISSUE THREAD

**Issue by jjmartin** [maptz/Maptz.VSCode.Extensions.CamelCaseNavigation#16]
When using ctrl-right (and presumably ctrl-left) on a long line that extends past the right side of the visible screen, the editor does not move keep the cursor visble (ie. Scroll the screen/text to the left as you continue to go more right)

**Comment by Ardeshir81** [comment]
Yep! I have this too!
It is not just right, it doesn't move at all, neither left, nor right. 

I have extension v 0.3.48
visual studio Version: 1.26.1
Ubuntu 18.04

**Comment by maptz** [comment]
Very good point. I'm looking into this.

**Comment by maptz** [comment]
Ok. I've got this working now. It should be up and running in the next release.
