### ISSUE TITLE
Underscore separated words

### ISSUE THREAD

**Issue by salokanto** [maptz/Maptz.VSCode.Extensions.CamelCaseNavigation#17]
The extension works perfectly with camel case words, but the behavior is sub-optimal for words separated with underscores — it stops at both sides of an underscore, and deletion doesn't delete the remaining (trailing or leading) underscore automatically.

In many programming languages you have both underscore and camel case separated names, so it would be much nicer to just use the same commands (i.e. key presses) to navigate regardless of the naming of a variable.

**Comment by maptz** [comment]
So to clarify, you would like to count `_something` as a whole camel-case word?

**Comment by maptz** [comment]
Perhaps, the optimal solution here would be to implement a mode which includes underscores. If you think this is valuable, please file this as a feature request.
