### ISSUE TITLE
Use ALT instead of CTRL for Mac users

### ISSUE THREAD

**Issue by scottyseus** [maptz/Maptz.VSCode.Extensions.CamelCaseNavigation#18]
On Mac machines, the CTRL + <- combination is already bound to switch workspaces. It seems that function has precedence over this plugin.

My workaround was to change the bindings myself in the VS Code settings, but it would be nice if we could automatically detect the user's platform and select the key bindings accordingly.

**Comment by maptz** [comment]
Hi, 

I'm not sure if I'm able to do platform specific keybindings in visual studio code. Perhaps I'm wrong. I'm looking into this. I've been tempted to remove all the default keybindings altogether, but then I think people wouldn't engage with the extension so well.

**Comment by maptz** [comment]
Ok. I was totally wrong about that. It is possible to implement per-platform keybindings. I've updated this for the Mac platofrm.
