### ISSUE TITLE
Tab indentation, line starting with lowercase

### ISSUE THREAD

**Issue by wierzbowski** [maptz/Maptz.VSCode.Extensions.CamelCaseNavigation#19]
Hi! CamelCaseNavigation is an awesome little extension, but I have one little quirk when working on files indented with tabs and when the line begins with lowercase letter.

As on the picture below, in line 3 it wouldn't stop before "do", but right after it. Line 5 which is indented with spaces works great. I would like the cursor to stop at where the red line is.

![image](https://user-images.githubusercontent.com/14241804/44569695-850f7980-a77b-11e8-972f-7a1a5da3a2ba.png)

Any chance for fix for that?

**Comment by maptz** [comment]
You're absolutely right about this. I'll look at changing this now.

**Comment by maptz** [comment]
Ok. I've pushed this change. So this issue should be resolved. Let me know if you have any further issues.

**Comment by wierzbowski** [comment]
Thanks! Works great now. Only other problem I can think of is, when I camel-case jump over the code
it doesn't trigger highlighting other instances of things under cursor (as shown on the picture), which normally happens when I move my cursor with arrows or mouseclick. That's actually a separate issue and not as important, but I thought I would toss it in in case you want to fix :)

![image](https://user-images.githubusercontent.com/14241804/47613851-718fd000-da96-11e8-9d5a-7f7d318e6ba4.png)

Great job on that extension!
