### ISSUE TITLE
Doesn't work with multiple rows selected

### ISSUE THREAD

**Issue by juanrb** [maptz/Maptz.VSCode.Extensions.CamelCaseNavigation#2]
Hey, nice extension, but I found an issue and forced me to uninstall it.

Scenario:
- Select multiple rows (cursor at the beginning of the line, hold ctrl+alt+down up to the third line in the example)
- Now press ctrl+shift+right in order to select only the first word from each line.

```
firstRow: some other text
secondRow: some other text
thirdRow: some other text

```

The problem:
It loses the multiple selection, selecting only the `first` substring.

**Comment by Noitidart** [comment]
I also have this situation. I am trying to make switch from Atom. I select multiple instances then I use the arrow keys like this in atom.

Here is a screencast of multi cursor camel case movement in atom:

![](https://lut.im/maDFtQXowq/W9pGOeyRR01MrI0F.gif)

**Comment by maptz** [comment]
Thanks all. I've updated it so the camel-casing works with multiple instances. 

This creates some behavioural peculiarities (e.g. when one cursor approaches a new line). Let me know if you reckon the behaviour could be improved.

**Comment by Noitidart** [comment]
Thanks @maptz ! Installing this back right away will let you know. :)

**Comment by Noitidart** [comment]
Hey @maptz - I'm on a Mac now, Ctrl + Shift + Left/Right works perfect, even with multiple. However just Ctrl + Left/Right is not working for me. :(

![](http://i.imgur.com/hgIA8bI.png)

**Comment by maptz** [comment]
Thanks for testing @Noitidart .

I've just booted it up in my Mac partition and you're absolutely right. I'd need to do a bit more research, but it looks possible that `Ctrl+Left` and `Ctrl+Right` arrows are reserved by the OS for navigating between desktops. In this case, I think it's better to use another key binding on OSX. 

My OSX isn't too hot. Is the default word traversal on OSX `Alt+Left` and `Alt+Right`? If so, perhaps on that platform that is better keybinding. What do you think?

**Comment by Noitidart** [comment]
Hey @maptz please excuse the long delay in my reply. 

* Alt + Left and Alt + Right is the correct traversal for word boundary. 
* Cmd + Left and Cmd + Right is start and end of line

I would have absolutely LOVED Ctrl + Left and Ctrl + Right for Mac it makes so much sense. I didn't know it was for switching desktops. :( I'll see if I can unreserve that and let you know.

**Comment by maptz** [comment]
Hey @Noitidart ,

Here is a workaround for your issue on OSX:

Go to `System Preferences > Keyboard > Shortcuts > Mission Control` and change the settings for "Move left a space" and "Move right a space" or disable them completely.

This gives VS code back access to the `Ctrl+Left` and `Ctrl+Right` key bindings.

**Comment by Noitidart** [comment]
Hey @maptz I was able to disable the Ctrl + left/right on mac! And now this extension works perfectly thank you!

This is how I disabled it on mac:

![](http://i.imgur.com/xSepEAd.png)

I changed it to command + right/left
