### ISSUE TITLE
Feature Request: remove camelCase with ctrl+backspace

### ISSUE THREAD

**Issue by Ardeshir81** [maptz/Maptz.VSCode.Extensions.CamelCaseNavigation#20]
HI!Thanks for this great extension.

I also want ctrl+backspace & ctrl+delete remove words only to the next camel, not the whole word/variable name.

**Comment by maptz** [comment]
Hi ,

By default this command is bound to `ctrl+shift+backspace`. You can override this behaviour manually if you'd like in your settings, or do you think this would be a better default?

**Comment by maptz** [comment]
I've implemented this change as a default.

**Comment by Ardeshir81** [comment]
Hooray! Yep! I think default is good!
Because if someone is looking for camelCase plugin, so he is into camels : )))
and he/she wants camels everywhere

**Comment by Hum4n01d** [comment]
Shouldn't the default keybind for this be `alt+backspace`?
