### ISSUE TITLE
This extension is not installable on any currently installed products.

### ISSUE THREAD

**Issue by stefanitsky** [maptz/Maptz.VSCode.Extensions.CamelCaseNavigation#21]
![image](https://user-images.githubusercontent.com/22547214/46133302-d57d6980-c248-11e8-821f-59c1d2817830.png)

VSIXInstaller.log:

> 27/09/2018 11:28:50 - Microsoft VSIX Installer
> 27/09/2018 11:28:50 - -------------------------------------------
> 27/09/2018 11:28:50 - vsixinstaller.exe version:
> 27/09/2018 11:28:50 - 15.8.3252
> 27/09/2018 11:28:50 - -------------------------------------------
> 27/09/2018 11:28:50 - Command line parameters:
> 27/09/2018 11:28:50 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,S:\Downloads\maptz.camelcasenavigation-0.3.48.vsix
> 27/09/2018 11:28:50 - -------------------------------------------
> 27/09/2018 11:28:50 - Microsoft VSIX Installer
> 27/09/2018 11:28:50 - -------------------------------------------
> 27/09/2018 11:28:51 - Initializing Install...
> 27/09/2018 11:28:51 - Extension Details...
> 27/09/2018 11:28:51 - 	Identifier         : camelcasenavigation
> 27/09/2018 11:28:51 - 	Name               : Camel Case Navigation
> 27/09/2018 11:28:51 - 	Author             : maptz
> 27/09/2018 11:28:51 - 	Version            : 0.3.48
> 27/09/2018 11:28:51 - 	Description        : Provides Camel Case cursor navigation for the Visual Studio Code editor.
> 27/09/2018 11:28:51 - 	Locale             : en-US
> 27/09/2018 11:28:51 - 	MoreInfoURL        : 
> 27/09/2018 11:28:51 - 	InstalledByMSI     : False
> 27/09/2018 11:28:51 - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
> 27/09/2018 11:28:51 - 
> 27/09/2018 11:28:51 - 	SignatureState     : Unsigned
> 27/09/2018 11:28:51 - 	Supported Products : 
> 27/09/2018 11:28:51 - 		Microsoft.VisualStudio.Code
> 27/09/2018 11:28:51 - 			Version : 
> 27/09/2018 11:28:51 - 
> 27/09/2018 11:28:51 - 	References         : 
> 27/09/2018 11:28:51 - Signature Details...
> 27/09/2018 11:28:51 - 	Extension is not signed.
> 27/09/2018 11:28:51 - 
> 27/09/2018 11:28:51 - Searching for applicable products...
> 27/09/2018 11:28:51 - Found installed product - Global Location
> 27/09/2018 11:28:51 - Found installed product - Visual Studio Community 2017
> 27/09/2018 11:28:51 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
>    at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
>    at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
>    at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
>    at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
>    at VSIXInstaller.App.Initialize()
>    at System.Threading.Tasks.Task`1.InnerInvoke()
>    at System.Threading.Tasks.Task.Execute()

**Comment by maptz** [comment]
Hi, 

It looks like you are trying to install this into Visual Studio proper, not Visual Studio Code. How are you trying to install this?
