### ISSUE TITLE
[Feature request] Use native navigation

### ISSUE THREAD

**Issue by Bublade** [maptz/Maptz.VSCode.Extensions.CamelCaseNavigation#22]
This extension is amazing, I'm missing one feature though. The ability to still use the native navigation. In some cases. when using multi selection the lines are not always the same amount of CamelCases. In which I did like to use the native navigation.

It would be great if the native navigation could be used by adding the ALT key when navigating.

**Comment by maptz** [comment]
I'm pretty sure you can do this just by remapping your keybindings to the default commands which this extension override. So rebind the commands like `cursorWordStartLeft` and `cursorWordStartLeftSelect`.
