### ISSUE TITLE
on camelCaseNavigation, refrences of same variable is not highlighted

### ISSUE THREAD

**Issue by aghArdeshir** [maptz/Maptz.VSCode.Extensions.CamelCaseNavigation#23]
HI!
This plugin is amazing!
Thanks!
I'm into camels too :)

BTW, VSCode has a feature that when the cursor moves over a variable, all of it's references inside the same file are highlighted (screenshot below)
But when navigation is done through camelCase plugin, the highlighting doesn't appear.

![screenshot 7](https://user-images.githubusercontent.com/5755214/48312532-4ee8d580-e5c5-11e8-926b-c87a53a20b79.png)

Thanks for your plugin.

**Comment by Ardeshir81** [comment]
HI! Yes I do still have.
I recorded this GIF right now:

![maptz](https://user-images.githubusercontent.com/5755214/51520182-39e7b880-1e38-11e9-8fab-fe00fcc818ae.gif)

Windows 10
I have VSCode 1.30.2
Your plugin@ 0.3.51

I just recorded this HTML portion (its in a `.vue` file), but in happpens in `.HTML` & `.JS` files (I mean it happens everywhere for me)

**Comment by maptz** [comment]
@Ardeshir81  are you sure this isn't the designed VS Code behaviour for HTML where only the closing tag is highlighted? I'm seeing other variable instances highlighted in .js and .cs files with the extension enabled.

**Comment by Ardeshir81** [comment]
Yeah! I will record more GIFs tomorrow

**Comment by maptz** [comment]
Hi @Ardeshir81 

It would be great to see more about what problem you're having.

**Comment by Ardeshir81** [comment]
wow @maptz thanks for reminder!
I actually forgot : __shame__ : : __shame__ : : __shame__ : 
: ))

here you go
I hope I could demonstrate what I mean in this GIF

![camel-case-test](https://user-images.githubusercontent.com/5755214/52163904-620bcd00-26fe-11e9-8e14-c74c0d975a65.gif)


Thanks for this great job!

**Comment by maptz** [comment]
Thanks @Ardeshir81. It would be great if you could explain a bit more. In the HTML version, are you expecting all instances of `span` to be highlighted?

**Comment by Ardeshir81** [comment]
HI!
I'm indicating in this example that when I use right & left arrows, highlighting appears. But when I'm using Ctrl+Right & Ctrl+Left arrows (i.e. using camelCase plugin) it doesn't.

If you notify in HTML , when I scroll through `span` letters, letter by letter (e.g. left arrow) the highlighting works. But when I do Ctrl+RightArrow (i.e. jumping from last/third/second letter to before letter `s`) the highlighting doesn't appear.

I hoped you could recognize I'm using Ctrl from seeing the caret jump.

**Comment by Ardeshir81** [comment]
![camel-case-test2](https://user-images.githubusercontent.com/5755214/52190662-a198fd00-2855-11e9-9a08-27edc4c4aa5a.gif)

**Comment by maptz** [comment]
Aha. Doh. Now I understand. Thanks for the clarification! Very good point. I'll look into this.

**Comment by maptz** [comment]
Sorry. I've just looked into this again tonight and I can't see an easy way of fixing it.

**Comment by alaaltoros** [comment]
Visual Studio doesn't highlight the references of the symbol when you start word navigation (ctrl + <- / ctrl + ->).

**Comment by maptz** [comment]
Anybody know how to force the VS editor to update the reference highlighting?

**Comment by Ardeshir81** [comment]
I'm working on this

**Comment by maptz** [comment]
Hi, As this feature is now part of VS Code, I won't be updating this repository. Feature requests should be made to the VS Code team.
