### ISSUE TITLE
Icon for the extension

### ISSUE THREAD

**Issue by emanuelescarabattoli** [maptz/Maptz.VSCode.Extensions.CamelCaseNavigation#29]
It would be nice if the extension had an icon to make it easily recognizable in marketplace. The icon will also help to make the extension more than "just another vs code extension".

If you need some help to draw the icon, maybe I can help you to create one! :)

**Comment by maptz** [comment]
Hi @emanuelescarabattoli 

Yes. It would be great to have a nice icon for this extension. Would be fantastic to have some help here as it's not in my skillset.

Any ideas?

**Comment by emanuelescarabattoli** [comment]
Hi! @maptz 

Maybe something like this?

![ccn](https://user-images.githubusercontent.com/38425260/73797221-b8976580-47af-11ea-8188-227b6bc1ffcf.png)

**Comment by emanuelescarabattoli** [comment]
It is only an idea :)

**Comment by maptz** [comment]
Simple and nice. Well done. 

Personally, I'm not sure about the text as it looks a tiny bit imbalanced, and it won't read well at small icon size. Do you think it might work to distil it down to the small 'c' and the big 'C' somehow?

**Comment by emanuelescarabattoli** [comment]
You are right!

Here some fix and other assets, if useful.

![ccn_64](https://user-images.githubusercontent.com/38425260/73811076-c1e8f800-47d8-11ea-9392-e5118cfaf534.png)
![ccn_128](https://user-images.githubusercontent.com/38425260/73811077-c2818e80-47d8-11ea-9328-451f99c7d063.png)
![ccn_256](https://user-images.githubusercontent.com/38425260/73811080-c2818e80-47d8-11ea-91db-a526313c0578.png)

**Comment by maptz** [comment]
Good work. I've merged this into the repo. Many thanks @emanuelescarabattoli

**Comment by emanuelescarabattoli** [comment]
It look cool in marketplace!! @maptz

**Comment by maptz** [comment]
Yeah. Good job
