### ISSUE TITLE
Doesn't work on accented words

### ISSUE THREAD

**Issue by 0x3333** [maptz/Maptz.VSCode.Extensions.CamelCaseNavigation#3]
If you try to navigate over accented words it stops on accented letters.

__Example:__

> Comit**ê** Gestor de Seguran**ç**a da Informa**çã**o

It stops over `ê`, `ç` and`ã`.

**Comment by maptz** [comment]
Thanks for spotting that. I've fixed it for that example. Please let me know if you spot any issues with other accented words.
