### ISSUE TITLE
Not working after latest update

### ISSUE THREAD

**Issue by the21st** [maptz/Maptz.VSCode.Extensions.CamelCaseNavigation#30]
I am now getting error `command 'extension.deleteCamelLeftCommand' not found`

**Comment by maptz** [comment]
Hi @the21st ,

Argh! My fault. A breaking change made its  way into 1.0.4 which should have been in preview. 

The command names have now changed as detailed in the readme. 

You should update any custom keybindings to read, for example:

"maptz.camelcasenavigation.deleteCamelLeftCommand"

**Comment by the21st** [comment]
Appreciate the quick fix!
