### ISSUE TITLE
[feature-request] Support camel case navigation in the `Rename` widget

### ISSUE THREAD

**Issue by kittaakos** [maptz/Maptz.VSCode.Extensions.CamelCaseNavigation#31]
The title describes it; I do not know if this is possible at all, but I would like to use the benefit of this extension when renaming a symbol in VS Code.

Steps to reproduce:
 - Set the text selection to a symbol in the editor,
 - Trigger `Rename` (<kbd>F2</kbd>),
 - Try to navigate with
   - <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>←</kbd> or 
   - <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>→</kbd> (on macOS),
 - It does not work as in the editor. The begging/end of the symbol is selected, instead of the next segment.

![screencast 2020-04-14 13-30-38](https://user-images.githubusercontent.com/1405703/79220894-279ad580-7e55-11ea-9073-019e81f03d47.gif)

Version: `camelcasenavigation@1.1.1`

Thank you for the great extension! 🥇

**Comment by maptz** [comment]
I'll look into this to see if it is possible, but I fear it's not exposed by the VS Code codebase yet.

**Comment by maptz** [comment]
Hi, As this feature is now part of VS Code, I won't be updating this repository. Feature requests should be made to the VS Code team.

**Comment by olyop** [comment]
Hi @maptz. Firstly great extension and appreicate your work. I saw your deprecation notice and have updated my keyboard shortcuts file like you mentioned but it still dosen't work in the rename widget. Any ideas how to get it to work there? Seems like there may be conflicting shortcuts.
