### ISSUE TITLE
Slow response, key repeat issues

### ISSUE THREAD

**Issue by TobiaszCudnik** [maptz/Maptz.VSCode.Extensions.CamelCaseNavigation#32]
Very useful feature, mandatory for many ppl migrating from intellij, but this implementation has:
- slow response (delay)
- key repeat issues (you can see the caret going back-and-forth)

It would be great to see those fixed, thanks.

**Comment by maptz** [comment]
Hi @TobiaszCudnik ,

I'm not seeing these issues on my machine. Are you seeing it on a clean install (i.e. with all other extensions switched off?) What's your system and OS?

**Comment by TobiaszCudnik** [comment]
You're right, its because of the version Im using.

Its [code-server 3.2.0](https://github.com/cdr/code-server/releases/tag/3.2.0). Native vscode fine well, so I guess camel jumps require some info from the server, in opposition to the regular ctrl/alt+arrow navigation, which works well.

I've opened a [ticket on code-server](https://github.com/cdr/code-server/issues/1663) to investigate.

**Comment by TobiaszCudnik** [comment]
I guess its a **wontfix** regarding implementing camel-jump the same way word-jump is implemented?

**Comment by maptz** [comment]
Hi,

I'm not sure what you mean. Can you clarify?

**Comment by TobiaszCudnik** [comment]
Camel-jumps suffer from lags (on code-server) unlike build-in word-jumps, whereas both are quite similar. I suppose thats because the implementation differs?

**Comment by maptz** [comment]
I see. Just out of interest, does the (relatively new) built-in camel jumping work well on code-serve?

**Comment by TobiaszCudnik** [comment]
This works perfectly fine
```
{
  "key": "ctrl+right",
  "command": "cursorWordPartRight",
  "when": "textInputFocus"
},
```
