### ISSUE TITLE
toggle configuration doesn't work

### ISSUE THREAD

**Issue by avalenti89** [maptz/Maptz.VSCode.Extensions.CamelCaseNavigation#33]
I tried to copy the configuration from the readme to my user settings file and when I try to toggle the caseNavigation I get "command 'camelcasenavigation.toggleCamelMode' not found" error.
![image](https://user-images.githubusercontent.com/19409732/82645077-9caab900-9c12-11ea-8a88-525aab1788df.png)

I found that there could be an error on the readme example: "maptz.camelcasenaviation" instead of "maptz.camelcasenavigation" (you missed a "g" in naviGation).
![image](https://user-images.githubusercontent.com/19409732/82645138-b3511000-9c12-11ea-8aea-b01da2aeb936.png)
I tried to fix it and it doesn't work either.

In my settings.json, the camelcase configuration is dark
![image](https://user-images.githubusercontent.com/19409732/82645044-8e5c9d00-9c12-11ea-952d-c443f71fa808.png)

**Comment by maptz** [comment]
Thanks for letting me know. It should definitely be: `maptz.camelcasenavigation`  The property should be `isCamelNavigationOnByDefault`. I'll look into it over the weekend though and make sure the docs are updated, and that it's working correctly.

**Comment by maptz** [comment]
Thanks. I've updated the documentation and will publish this soon. 

It's working for me with the correct settings, though I do have to restart the application after changing `isCamelNavigationOnByDefault`. This is by design, as this setting determines how the CamelCase feature works on startup. 

Does this solve your issue?

**Comment by avalenti89** [comment]
Thanks, but it doesn't work :-( Same dark settings, same command not found error

**Comment by maptz** [comment]
hmm. Is this workspace or global settings?

Which version of Vs code?

**Comment by avalenti89** [comment]
Settings: User/settings.json
Vs code version: 1.45.1 (April 2020)

**Comment by maptz** [comment]
Thanks. The `package.json` was missing a configuration setting which was why the settings were grayed out. 

I can't replicate the command not found issue yet though. 

Version 1.1.2 will push out in an hour with the configuration change. See if it fixes things for you.

**Comment by avalenti89** [comment]
Still not, but I found the problem:
![image](https://user-images.githubusercontent.com/19409732/83606208-80dfd500-a579-11ea-8a9d-e127ce356995.png)
You missed "maptz" before "camelcasenavigation". The readme is not up to date with the changelog.

![image](https://user-images.githubusercontent.com/19409732/83606367-c6040700-a579-11ea-8fcb-d728460f6de5.png)

**Comment by maptz** [comment]
Well spotted. Thanks. That's updated in the Readme
