### ISSUE TITLE
Left over `console.log` in `isSpace` method

### ISSUE THREAD

**Issue by jessejenks** [maptz/Maptz.VSCode.Extensions.CamelCaseNavigation#34]
There is a stray `console.log` in the [`isSpace`](https://github.com/maptz/Maptz.VSCode.Extensions.CamelCaseNavigation/blob/master/ts/CamelCasing.ts#L81) method. Not a big issue at all but I thought you might want to know about it.

**Comment by maptz** [comment]
Thanks. Fixed.
