### ISSUE TITLE
[feature-request] can this be achieved on mouse selection as well?

### ISSUE THREAD

**Issue by toriqo** [maptz/Maptz.VSCode.Extensions.CamelCaseNavigation#36]
can the same selection be applied when double clicking part of a camelCaseSymbol?

for example, if clicking Case in camelCaseSymbol, only select Case.

thanks, great extension otherwise! :)

**Comment by maptz** [comment]
Hi @toriqo ,

It's a great idea, but - as far as I can tell - there's no way to do this using the VS Code extension API surface. I think some changes would be necessary to the VS Code build itself to get this to work. 

I'll leave this open, while I do some digging though

**Comment by toriqo** [comment]
cool, thanks!

**Comment by maptz** [comment]
Hi, As this feature is now part of VS Code, I won't be updating this repository. Feature requests should be made to the VS Code team.
