### ISSUE TITLE
Possible to change keys used for navigation?

### ISSUE THREAD

**Issue by nabelekt** [maptz/Maptz.VSCode.Extensions.CamelCaseNavigation#37]
Is there any way to change the keys used for camel case navigation so that the default behavior of Ctrl+Arrow can be retained, and something custom can be used for this?

**Comment by maptz** [comment]
Yes. You just need to add keybindings for the commands:

```
- maptz.camelcasenavigation.extendCamelLeftCommand
- maptz.camelcasenavigation.extendCamelRightCommand
- maptz.camelcasenavigation.moveCamelLeftCommand
- maptz.camelcasenavigation.moveCamelRightCommand
```
