### ISSUE TITLE
Doesn't work for Cyrillic

### ISSUE THREAD

**Issue by ForNeVeR** [maptz/Maptz.VSCode.Extensions.CamelCaseNavigation#4]
Consider this Cyrillic phrase: `широкая электрификация южных губерний`. It should be considered as a four-word phrase, but `CamelCaseNavigation` seems to count every letter as a distinct word instead (when navigating with `Ctrl + arrows`).

As a counterexample, `НовыйКомОбъект` should be three words.

**Comment by ForNeVeR** [comment]
I have the fix for the issue, but I cannot send the pull request before the project license is defined (see #5).

**Comment by maptz** [comment]
Well done @ForNeVeR . I've incorporated this into the project. 

Thanks for your help. I'm an open source newbie really (coding is a hobby, not my day job), so all the help is great. 

I'm going to move the character checks out of the `CamelComponent` class into their own class.

**Comment by ForNeVeR** [comment]
@maptz you're welcome. Open-source community is warm and helpful. It's good to see anyone aboard :)
