### ISSUE TITLE
Project license?

### ISSUE THREAD

**Issue by ForNeVeR** [maptz/Maptz.VSCode.Extensions.CamelCaseNavigation#5]
Could you please state the license somewhere? Currently the license is undefined and that creates problems regarding contribution.

If you have no preferred license variant, I'd suggest to use MIT license.

**Comment by maptz** [comment]
Great point. Just starting out with OSS, and wil put a license on now.

**Comment by ForNeVeR** [comment]
Thank you, that's very nice!
