### ISSUE TITLE
DiacriticsHelpers is unused

### ISSUE THREAD

**Issue by ForNeVeR** [maptz/Maptz.VSCode.Extensions.CamelCaseNavigation#6]
Currently a whole portion of the extension code is occupied by (seemingly unused) [`DiacriticsHelpers`](https://github.com/maptz/Maptz.VSCode.Extensions.CamelCaseNavigation/blob/4cafccbeb40d94d60e0831da185ae339d013e696/src/ts/CamelCasing.ts#L204-L302) class. Probably we need to delete this?

**Comment by maptz** [comment]
Yes. Great point. Done.
